### ISSUE TITLE
Voodoo doll goes brrrrr

### ISSUE THREAD

**Issue by UndeadPotatoes** [Joespresso/Hate2Wait#1] opened 2022-03-07 20:25 UTC
The voodoo doll goes as fast as the printers. Pretty broken to use and it destroys your fps.

**Comment by Joespresso** [comment] 2022-03-07 20:46
Hey @UndeadPotatoes !  I just tested this with a sacrifice/command run and it works normal on my end.  Can you tell me what other mods you have installed and what items you had?  Thanks!

**Comment by UndeadPotatoes** [comment] 2022-03-07 20:52
Sure, tried it with a few new ones. EggsSkills, ShowDeathCause, VoidSacrifice as well as BiggerBazaar and Risky_Artifacts.  Don't know the items though, a friend found the bug not me.

**Comment by Joespresso** [comment] 2022-03-07 20:57
@UndeadPotatoes hmmm I suspect it is actually working as intended.  Even without mods you can get equipment cooldowns very low.  If your friend had a gesture of the drowned and a soulbound catalyst then that combo pretty easily can create that behavior.  If they run into the issue again please let me know, also I would like to know if it is Dolls are dropping very fast or going off fast.  since many dolls dropping can create a big effect, or a doll triggering the death effect more often than usual could do it.

**Comment by UndeadPotatoes** [comment] 2022-03-07 21:01
It wasn't that he was throwing them ererywhere, the problem was that the dolls had an insanely fast tick rate.

**Comment by Joespresso** [comment] 2022-03-07 21:02
Gotcha.  let me look for that really quick

**Comment by Joespresso** [comment] 2022-03-07 23:45
@UndeadPotatoes After a long run I was able to again test.  I am going to add show death cause and see if that might be the culprit

**Comment by Joespresso** [comment] 2022-03-07 23:54
@UndeadPotatoes I installed all the mods you mentioned and still was not able to reproduce the behavior.  Any other ideas before I close the issue?

**Closed as completed** 2022-03-10 19:28 UTC
